### PR TITLE
Tests

### PR DESCRIPTION
**Pull request by loechel**
Add more tests

Work in Progress, Pull Request to see Travis-CI running our tests

### CODE REVIEW

**Comment by gforcada** [comment]
@loechel I enabled coveralls on this repo, would you mind adding the missing bits on .travis.yml and README? https://coveralls.io/github/plone/plone.versioncheck

**Comment by loechel** [comment]
@gforcada I will take care of this. Thank you.

**Comment by loechel** [comment]
@gforcada could we disable those coveralls messages?

**Comment by loechel** [comment]
ok, now we have a base for future tests and check if something change on modification.
@jensens could you look and merge, please.

**Comment by loechel** [comment]
I see that all tests on travis-ci are now failing. I have fixed problems that needs a buildout run so that a tracking file is written.

Current errors came from the trying to identify consol width. we need a mock or fixture for that.

**Comment by gforcada** [comment]
@loechel done, coveralls should not send more messages

**Comment by loechel** [comment]
OK seems to work now.

@jensens could you please review and merge. 
It shouldn't have touched any source code itself, except on in formatter where I fixed a typo.

@gforcada why do we now have a jenkins task on this package?

**Pull request merged**
